### ISSUE TITLE
Duplicated Unique Id

### ISSUE THREAD

**Issue by lp55** [basti242/homeassistant_lg_therma_v_modbus#15]
Hi. While using the modbus_lg_heatpump.yaml, home assistant complained about "Modbus lg_heatpump/sensor.hp_room_air_temp_circuit2 is duplicate, second entry not loaded.". It's on [L117](https://github.com/basti242/homeassistant_lg_therma_v_modbus/blob/3e67dd9addd052f73915bf69561615b08fec7d73/modbus_lg_heatpump.yaml#L117) and on [L279](https://github.com/basti242/homeassistant_lg_therma_v_modbus/blob/3e67dd9addd052f73915bf69561615b08fec7d73/modbus_lg_heatpump.yaml#L279). I'm not sure what they should be renamed as.
Thank you

**Comment by basti242** [comment]
You are right, thanks for attention.
It is fixed in code.

**Comment by basti242** [comment]
closed
