### ISSUE TITLE
Source of Information and target device information?

### ISSUE THREAD

**Issue by CosmicDuck** [basti242/homeassistant_lg_therma_v_modbus#2]
Hello,

I bougth a Therma V R290 with PHCS0.ENCXLEU so I would like to ask where you got the information.
Official documentation? Reverse Engeneering? …?

Which exact LG Heatpump do you have? This could be helpful to understand the registers more with my LG.

**Comment by basti242** [comment]
Hi, 

I apologise for my late reply. 
Where do you have found this number of your heatpump?
I have taken most of the information from various forums or documentation.
Please have a look at the documentation I have created over the last few days. If you need more information, please feel free to ask me.

https://github.com/basti242/homeassistant_lg_therma_v_modbus

BR
Sebastian

**Comment by basti242** [comment]
closed
