### ISSUE TITLE
Code für Beispielanzeige in HomeAssistant

### ISSUE THREAD

**Issue by containerguy** [basti242/homeassistant_lg_therma_v_modbus#5]
Moin basti242,
echt ein super Projekt bisher! Wäre es möglich, den Code für das Dashboard in HomeAssistant bereitzustellen? Das wäre echt super!

**Comment by basti242** [comment]
Moin,

Klar kann ich machen. Wird aber erst Abends was. 

Gruß
Basti

**Comment by basti242** [comment]
Habs zur Anleitung hinzugefügt.
